Repository nephila/djangocms-blog, pull requests merged in 2018-04, with the labels that each got.

#447 Fix jquery path in Django 1.9+
  HISTORY.rst
  djangocms_blog/cms_wizards.py
Labels: status: review, type: bug

#449 Feature/customisable ckeditor 0.9
  djangocms_blog/models.py
  docs/settings.rst
Labels: status: approved, type: feature

#451 Fix __str__ for Post and BlogCategory w/ no translation
  djangocms_blog/models.py
  tests/test_models.py
Labels: status: approved, type: bug
