Repository nephila/djangocms-blog, pull requests merged in 2020-05, with the labels that each got.

#552 Pin django cms on python 2.7
  .travis.yml
  tox.ini
Labels: type: bug

#549 Add experimental support for django-app-enabler
  MANIFEST.in
  addon.json
  djangocms_blog/addon.json
Labels: type: feature

#553 Add support for django 3.0
  .travis.yml
  cms_helper.py
  djangocms_blog/admin.py
  djangocms_blog/feeds.py
  djangocms_blog/liveblog/models.py
  djangocms_blog/models.py
  docs/features/channels.rst
  tests/test_models.py
  tox.ini
Labels: type: feature

#551 Improve documentation for meta tags
  docs/installation.rst
Labels: type: bug, type: documentation

#559 Avoid admin exception for related posts when config is None
  djangocms_blog/admin.py
Labels: type: bug

#561 Fix channels support
  cms_helper.py
  djangocms_blog/liveblog/consumers.py
  djangocms_blog/liveblog/models.py
  djangocms_blog/liveblog/routing.py
  djangocms_blog/liveblog/static/liveblog/js/liveblog.js
  docs/features/channels.rst
  requirements-test.txt
  tests/test_liveblog.py
  tests/test_models.py
  tests/test_plugins.py
  tests/test_utils/routing.py
  tox.ini
Labels: type: bug

#562 Fix error when overriding templates folder
  djangocms_blog/cms_plugins.py
  tests/test_plugins.py
Labels: type: bug

#543 Drop python2, Django < 2.2, django CMS < 3.7
  .travis.yml
  README.rst
  cms_helper.py
  djangocms_blog/__init__.py
  djangocms_blog/admin.py
  djangocms_blog/apps.py
  djangocms_blog/cms_appconfig.py
  djangocms_blog/cms_apps.py
  djangocms_blog/cms_menus.py
  djangocms_blog/cms_plugins.py
  djangocms_blog/cms_toolbars.py
  djangocms_blog/cms_wizards.py
  djangocms_blog/feeds.py
  djangocms_blog/fields.py
  djangocms_blog/forms.py
  djangocms_blog/liveblog/__init__.py
  djangocms_blog/liveblog/apps.py
  djangocms_blog/liveblog/cms_plugins.py
  djangocms_blog/liveblog/consumers.py
  djangocms_blog/liveblog/models.py
  djangocms_blog/liveblog/routing.py
  djangocms_blog/managers.py
  djangocms_blog/media/__init__.py
  djangocms_blog/media/base.py
  djangocms_blog/models.py
  djangocms_blog/search_indexes.py
  djangocms_blog/settings.py
  djangocms_blog/sitemaps/__init__.py
  djangocms_blog/taggit_urls.py
  djangocms_blog/templatetags/__init__.py
  djangocms_blog/templatetags/djangocms_blog.py
  djangocms_blog/urls.py
  djangocms_blog/views.py
  requirements-test.txt
  setup.py
  tests/base.py
  tests/media_app/cms_plugins.py
  tests/media_app/models.py
  tests/test_indexing.py
  tests/test_liveblog.py
  tests/test_media.py
  tests/test_menu.py
  tests/test_models.py
  tests/test_plugins.py
  tests/test_setup.py
  tests/test_toolbar.py
  tests/test_utils/blog_urls.py
  tests/test_utils/models.py
  tests/test_utils/routing.py
  tests/test_utils/urls.py
  tests/test_views.py
  tests/test_wizards.py
  tox.ini
Labels: status: analysis, type: feature

#566 Bugfix/#565 individual test cases
  CONTRIBUTING.rst
Labels: status: approved, type: documentation

#576 Fix GA behavior on pull request
  .github/workflows/test.yml
  changes/575.bugfix
  tasks.py
Labels: type: bug

#578 Fix coveralls failure on pull request in GA
  .github/workflows/test.yml
  changes/577.bugfix
Labels: type: bug

#574 [setup.cfg] Add dependency to lxml
  setup.cfg
Labels: status: approved, type: bug

#582 Fix link in PR template
  .github/pull_request_template.md
  changes/581.bugfix
Labels: type: bug, type: documentation

#583 Remove deprecated functions
  changes/571.feature
  djangocms_blog/feeds.py
  djangocms_blog/models.py
  djangocms_blog/search_indexes.py
  tests/test_models.py
  tests/test_toolbar.py
  tests/test_utils/admin.py
  tests/test_views.py
Labels: status: approved, type: feature
