Repository nephila/djangocms-blog, pull requests merged in 2020-06, with the labels that each got.

#588 Add PyUp configuration
  .pyup.yml
Labels: type: feature

#585 Skip haystack index creation if aldryn-search is not installed
  .github/workflows/test.yml
  changes/584.bugfix
  cms_helper.py
  djangocms_blog/search_indexes.py
  docs/installation.rst
  requirements-test.txt
  tests/test_indexing.py
  tox.ini
Labels: type: bug

#590 Added blog post extensions
  changes/569.feature
  djangocms_blog/admin.py
  docs/features/extensions.rst
  docs/features/index.rst
  tests/test_extension.py
  tests/test_utils/admin.py
  tests/test_utils/migrations/0002_auto_20200516_1230.py
  tests/test_utils/models.py
  tests/test_utils/templates/blog.html
Labels: status: review, type: feature

#592 Skip towncrier on develop / master branch
  changes/591.bugfix
  tasks.py
Labels: type: bug

#594 Tweak linting
  .pre-commit-config.yaml
  changes/593.misc
  pyproject.toml
  tox.ini
Labels: type: feature

#599 Set default pytest configuration
  changes/598.bugfix
  tox.ini
Labels: type: bug

#600 Fix extra migration when customizing BLOG_PLUGIN_TEMPLATE_FOLDERS
  changes/597.bugfix
  djangocms_blog/migrations/0024_auto_20160706_1524.py
Labels: type: bug

#601 Fix extra migration when customizing BLOG_PLUGIN_TEMPLATE_FOLDERS
  djangocms_blog/migrations/0024_auto_20160706_1524.py
Labels: type: bug

#602 Update translation files
  djangocms_blog/locale/ar/LC_MESSAGES/django.mo
  djangocms_blog/locale/ar/LC_MESSAGES/django.po
  djangocms_blog/locale/de/LC_MESSAGES/django.mo
  djangocms_blog/locale/de/LC_MESSAGES/django.po
  djangocms_blog/locale/es/LC_MESSAGES/django.mo
  djangocms_blog/locale/es/LC_MESSAGES/django.po
  djangocms_blog/locale/et/LC_MESSAGES/django.mo
  djangocms_blog/locale/et/LC_MESSAGES/django.po
  djangocms_blog/locale/fr/LC_MESSAGES/django.mo
  djangocms_blog/locale/fr/LC_MESSAGES/django.po
  djangocms_blog/locale/it/LC_MESSAGES/django.mo
  djangocms_blog/locale/it/LC_MESSAGES/django.po
  djangocms_blog/locale/lt/LC_MESSAGES/django.mo
  djangocms_blog/locale/lt/LC_MESSAGES/django.po
  djangocms_blog/locale/nb_NO/LC_MESSAGES/django.mo
  djangocms_blog/locale/nb_NO/LC_MESSAGES/django.po
  djangocms_blog/locale/nl/LC_MESSAGES/django.mo
  djangocms_blog/locale/nl/LC_MESSAGES/django.po
  djangocms_blog/locale/pl_PL/LC_MESSAGES/django.mo
  djangocms_blog/locale/pl_PL/LC_MESSAGES/django.po
  djangocms_blog/locale/pt_BR/LC_MESSAGES/django.mo
  djangocms_blog/locale/pt_BR/LC_MESSAGES/django.po
  djangocms_blog/locale/ru/LC_MESSAGES/django.mo
  djangocms_blog/locale/ru/LC_MESSAGES/django.po
  djangocms_blog/locale/sl/LC_MESSAGES/django.mo
  djangocms_blog/locale/sl/LC_MESSAGES/django.po
  djangocms_blog/locale/tr/LC_MESSAGES/django.mo
  djangocms_blog/locale/tr/LC_MESSAGES/django.po
Labels: type: feature

#609 Restore normal python versions declaration in tox
  .github/workflows/test.yml
  changes/606.bugfix
  tox.ini
Labels: type: bug

#610 Split linting GA to its own file
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/workflows/lint.yml
  .github/workflows/test.yml
  changes/608.bugfix
Labels: type: bug

#605 Clarify documentation regarding templates customization
  changes/595.bugfix
  docs/features/templates.rst
Labels: status: review, type: documentation

#612 Fix missing template folders selection in plugins
  changes/595.bugfix
  djangocms_blog/cms_plugins.py
  djangocms_blog/forms.py
  tests/test_plugins.py
Labels: type: bug

#611 Fix creating text plugin in wizard
  changes/607.bugfix
  djangocms_blog/cms_wizards.py
  djangocms_blog/settings.py
  docs/features/wizard.rst
  docs/settings.rst
  tests/test_wizards.py
Labels: type: bug
